CREATE DATABASE IF NOT EXISTS DB_NAME;

DROP USER IF EXISTS
	'DB_NAME_user'@'localhost';
CREATE USER
	'DB_NAME_user'@'localhost'
	IDENTIFIED BY 'DB_PASSWORD';

GRANT ALL PRIVILEGES
	ON DB_NAME.*
	TO 'DB_NAME_user'@'localhost';

FLUSH PRIVILEGES;

